# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a551b2e2d9b533230918a504185d2c0d72976c2aed8b57abefed1729566b08067874ec9cca7444fa6208c365aafe0aecc678aba9f8d12d583c345d5779da844

test:
  secret_key_base: 25623e1f7a733e30213ba0a95dbc869978330d700840a9e7bcb1671b191e2dd5cfc8998b9a15e7a24fa278da05e5b4e7177cade77e1d12e91e803cb4103e0602

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
